app:
    datasource:
        jdbc-url: jdbc:postgresql://localhost:5432/springbootdb
        username: postgres
        password: password
        pool-size: 30
        driver-class-name: org.postgresql.Driver

# spring.application.name=gitpod_version
